### ISSUE TITLE
Does not show up on lovelace

### ISSUE THREAD

**Issue by viseshrp** [iablon/HomeAssistant-Touchpad-Card#1]
Hi @iablon ,

Thanks for your work. I just installed and enabled Ollo's integration and then added the card from HACS Frontend. It looks like it installed properly, but I cannot find it in the list of cards in Lovelace when I click Add Card. I think I probably might be missing something.

**Comment by iablon** [comment]
Hi, you should search for touchpad remote for tv.
something like this
![Screenshot_20221230_232717_Home Assistant](https://user-images.githubusercontent.com/64681499/210116085-7c1f0ea7-7f1d-48da-b32e-66ff9b89fc70.jpg)
If still no luck try uninstalling from hacs and reinstall it again
