### ISSUE TITLE
Touchpad on iOS devices

### ISSUE THREAD

**Issue by groenmarsmannetje** [iablon/HomeAssistant-Touchpad-Card#2]
The touchpad doesn't appear on my iPad in iOS companion app. And on my iPhone the touchpad area is very small.

**Comment by iablon** [comment]
hi, since i don't have an apple device, I can't guarantee that the card works perfectly on an iphone, however I see what you are talking about so I tried to fix the problem and now it SHOUD work properly.

**Comment by groenmarsmannetje** [comment]
I can confirm that it is working now.
Thank you for your quick response
