### ISSUE TITLE
New Remote UI

### ISSUE THREAD

**Issue by HyperPickle** [iablon/HomeAssistant-Touchpad-Card#3]
Hi iablon, I wasn't sure how to contact you, so I opened up an issue to get your attention.

Before you released your Touchpad Card, I was looking for something very similar to work with the [Samsung TV Smart Integration](https://github.com/ollo69/ha-samsungtv-smart); I'm also using Ollo's fork. As there wasn't anything available, I made a remote UI myself with mushroom template cards as I still need to learn how to make full-blown integrations or custom cards. Thus, since I already went through the long process of testing, designing, etc, with my own remote UI. I hope sharing my code will help you with your custom touchpad card.

[RemoteUI-YAML.txt](https://github.com/iablon/HomeAssistant-Touchpad-Card/files/10390658/RemoteUI-YAML.txt)

**Comment by iablon** [comment]
Hi hyperpickle, thanks for using the card; in future releases will take in consideration your idea
