### ISSUE TITLE
Selecting an entity from the dropdown does not provide any options

### ISSUE THREAD

**Issue by Av4K100** [iablon/HomeAssistant-Touchpad-Card#4]
Selecting an entity from the dropdown does not provide any options to configure, it provides a message to say i must define a entity even if a entity is selected

**Comment by iablon** [comment]
can you provide a screeshot of what you are talking about?

**Comment by tarek52** [comment]
I’ve the same issue could you please guide me how to solve it

**Comment by iablon** [comment]
if you still want to use the card, update to v1.0.6 and the card should now work
