### ISSUE TITLE
The dropdown list not working 

### ISSUE THREAD

**Issue by tarek52** [iablon/HomeAssistant-Touchpad-Card#5]
@iablon 
The dropdown list to choose the entity not working 
Even when you edit with yaml not working. 

![IMG_5662](https://user-images.githubusercontent.com/35848621/234193262-f0aa0931-6fd7-4715-8353-68a69ca66fd8.png)
![IMG_5661](https://user-images.githubusercontent.com/35848621/234193276-d6afbd8f-eae9-48a6-8210-4871fae6e2e1.png)

**Comment by iablon** [comment]
Strange, I just tried to setup the card and had no issues, have you updated to v1.0.4? and also the second screenshot is strange it should be something like this instead:
```
type: custom:my-tv-card
entity: media_player.my_tv
```

**Comment by tarek52** [comment]
Yes I’m installing the latest version. 
I updated the yaml but still not working. 

![IMG_5663](https://user-images.githubusercontent.com/35848621/234213399-795461b1-2145-4950-9b20-7e8121e95884.png)
![IMG_5664](https://user-images.githubusercontent.com/35848621/234213413-eee45ed3-f698-44f5-89e6-dae3cb1d3a34.png)

**Comment by iablon** [comment]
You could try to reinstall it from hacs, and then clear te cache of companion app/web browse from where you are accessing homeassistant.
Do you see errors on homeassistant logs? Also can you access devtools from a compute to see if there are any errors?

**Comment by tarek52** [comment]
I tried to install it again & cleared cache with no luck and I found the below error 

![IMG_5665](https://user-images.githubusercontent.com/35848621/234233223-25eef333-fe7a-4892-9c19-01789e488294.jpeg)

**Comment by iablon** [comment]
what homeassistant version do you have? 
have you tried using a browser or another media player to configure the card?
if not please try that

**Comment by tarek52** [comment]
Yes I did with no luck. 

![IMG_5666](https://user-images.githubusercontent.com/35848621/234294189-26699075-d1e5-4427-9dec-9eff9dbd0132.jpeg)

**Comment by iablon** [comment]
it's difficul to diagnose without seeing the code and devtools, so if you can get the card code end send it that would be very helpful,or at least enter your browser dev tools(right click and inspect) to see if there are more helpful error messages.
also I tried reinstalling the card and had no errors so dont know what else to suggest

**Comment by iablon** [comment]
if you still want to use the card, update to v1.0.6 and the card should now work

**Comment by tarek52** [comment]
Thanks a lot it’s working now. I love it 😍
