### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by edionek** [iablon/HomeAssistant-Touchpad-Card#6]
![Screenshot_20230526_084009_Home Assistant](https://github.com/iablon/HomeAssistant-Touchpad-Card/assets/123167530/28a02683-8b09-4251-b76f-3a6e19e70391)
Request for help.  I know this is probably not the place I should write but I don't really know where to write.  The card looks very impressive, I would love to use it, but my knowledge is still probably too small.  I installed the Samsung Smart TV repository.  I configured them with the TV's IP address, name and token generated as instructed. And the integration works I installed your add-on.  In configuration, I selected an entity from Samsung Smart TV Integration, but I have information about setting up a custom component, and how do I configure it?  Sorry for my english and please help me.  I will just add that my TV is a Samsung series 7 and was produced after 2016 and it is Tizen

**Comment by iablon** [comment]
Update to v1.0.6, this should solve the issue
